# Generated by Django 6.0.3 on 2026-03-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='base_points',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
